Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2020-10, with the labels that each got.

#63 Add nominee: Kit Kit School
  nominees/kitkit-school.json
Labels: blocked, nomination

#69 Add nominee: Good Here
  nominees/good-here.json
Labels: blocked, nomination

#70 Add nominee: OpenLMIS
  nominees/openlmis.json
Labels: nomination

#71 MAINT: updated Primero info from form submission
  nominees/primero.json
Labels: blocked, nomination

#82 DOC: documented howto new release
  docs/development.md
Labels: Documentation

#72 BLD: add nada-data-catalog.json
  nominees/nada-data-catalog.json
Labels: nomination

#76 Add nominee: OpenCRVS
  nominees/open-civil-registration-and-vital-statistics.json
  nominees/opencrvs.json
Labels: nomination

#78 Add nominee: RexChain
  nominees/rexchain.json
Labels: nomination

#79 Add nominee: VaccineLedger
  nominees/vaccineledger.json
Labels: nomination

#77 Add nominee: Helping the diagnosis of infants affected by neonatal sepsis using machine learning
  nominees/presco.json
Labels: nomination

#75 Add nominee: CNBGuatemala - the Guatemala Online National Basic Curriculum
  nominees/cnb-guatemala.json
Labels: nomination

#92 BLD: opencrvs small edits [skip pr]
  nominees/opencrvs.json
  screening/opencrvs.json
Labels: enhancement

#91 MAINT: adjust CI checks to screening
  nominee-schema.json
  package.json
  screening-schema.json
  scripts/check-filenames.bash
  scripts/order-fields.js
Labels: enhancement

#93 Migrated submission data for Primero
  screening/primero.json
Labels: screening

#94 Removed duplicate for underAgeProtection fields
  nominees/cnb-guatemala.json
  nominees/tagcoding.json
  screening-schema.json
  screening/opencrvs.json
  screening/primero.json
  scripts/order-fields.js
Labels: enhancement
