Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2020-11, with the labels that each got.

#104 BLD: added mobile-wach.json
  CHANGELOG.md
  nominees/mobile-wach.json
Labels: nomination

#105 BLD: added geoprism-registry
  CHANGELOG.md
  nominees/geoprism-registry.json
Labels: nomination, pending review

#111 Migrate Apache Fineract submission data to JSON
  screening/apache-fineract.json
Labels: screening

#108 Add nominee: Geomancer: An Open-Source Framework for Geospatial Feature Engineering
  nominees/geomancer.json
Labels: nomination

#86 Add nominee: Telemesh
  nominees/telemesh.json
Labels: nomination

#107 Add nominee: X-Road® Data Exchange Layer
  nominees/x-road.json
Labels: nomination

#110 Add nominee: OpenG2P
  nominees/openg2p.json
Labels: nomination

#109 Add nominee: AI Powered Poverty Estimation
  nominee-schema.json
  nominees/ai-powered-poverty-estimation.json
Labels: nomination

#113 Migrate X-Road submission data to JSON
  screening/x-road.json
Labels: screening

#106 Add nominee: Mifos
  nominees/mifos-android.json
  nominees/mifos-community-app.json
  nominees/mifos-mobile.json
  nominees/mifos-web-app.json
Labels: nomination

#120 Add nominee: Standard for Public Code
  nominees/standard-for-public-code.json
Labels: nomination, pending review

#112 Migrate OpenG2P submission data to JSON
  nominees/openg2p.json
  screening/openg2p.json
Labels: screening

#125 Add nominee: DHIS2
  nominees/dhis2.json
  nominees/district-health-information-system-2.json
Labels: nomination

#128 Migrated MIFOS submission to JSON
  nominees/mifos-android.json
  nominees/mifos-community-app.json
  nominees/mifos-mobile.json
  nominees/mifos-web-app.json
  screening/mifos-android.json
  screening/mifos-community-app.json
  screening/mifos-mobile.json
  screening/mifos-web-app.json
  scripts/check-filenames.bash
  scripts/order-fields.js
Labels: screening

#130 Fixed typo error in screening schema
  screening-schema.json
  screening/apache-fineract.json
  screening/mifos-community-app.json
  screening/opencrvs.json
  screening/openg2p.json
  screening/primero.json
  screening/x-road.json
Labels: enhancement

#127 Add nominee: Wonder Tree
  nominees/wonder-tree.json
Labels: nomination

#134 Encode the Mojaloop submission into JSON
  screening/mojaloop.json
Labels: screening

#138 Add nominee: African Terrestrial Fibre Network Mapping Project (AfTerFibre)
  nominees/african-terrestrial-fibre-network-mapping-project.json
Labels: nomination, pending review

#147 Encode DHIS2 submission into JSON
  nominees/dhis2.json
  screening/dhis2.json
Labels: screening
