Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2020-12, with the labels that each got.

#155 Removed software tag from Global Digital Library nominee submission
  nominees/global-digital-library.json
Labels: pending review

#156 Update Mojaloop status from nominee to DPG
  nominees/mojaloop.json
Labels: pending review

#153 Avyantra health technologies nominee update
  nominees/avyantra-health-technologies.json
Labels: pending review

#139 Add nominee: CiviCRM
  nominees/civicrm.json
Labels: nomination

#119 Encode MOSIP submission into JSON and add it to unicef/publicgoods-candidates/screening
  nominees/modular-open-source-identity-plaform.json
  screening/modular-open-source-identity-plaform.json
Labels: pending review, screening

#141 Add nominee: Humansis
  nominees/humansis.json
Labels: duplicate, nomination

#150 Add nominee: openIMIS
  nominees/open-insurance-management-information-system.json
  nominees/openimis.json
Labels: nomination, pending review

#154 Add nominee: Cboard
  nominees/cboard.json
Labels: nomination, pending review

#159 Add nominee: Integreat
  nominees/integreat.json
Labels: nomination

#158 Add nominee: Oppia.org
  nominees/oppia.json
Labels: nomination

#177 Manually add nominee: The Atrium
  nominees/the-atrium.json
Labels: nomination

#175 Add nominee: CommCare
  nominees/commcare-android.json
  nominees/commcare-cloud.json
  nominees/commcare.json
Labels: nomination, pending review

#172 Add nominee: Juniper
  nominees/juniper.json
Labels: nomination, pending review

#152 Encode avyantra-health-technologies submission into JSON
  screening/avyantra-health-technologies.json
Labels: pending review, screening

#160 Add nominee: MET Norway Weather API
  nominees/met-norway-weather-api.json
  nominees/met-norway-weather.json
Labels: nomination
