Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2021-04, with the labels that each got.

#307 Add review
  reviews/OpenG2P-jcpickett1.json
Labels: crowdsourced review

#312 Add review
  reviews/Avyantra Health Technologies-ujjwalpratapsingh287.json
Labels: crowdsourced review, pending review

#316 Add review
  reviews/OpenG2P-Stockriii.json
Labels: crowdsourced review, pending review

#319 Add review
  reviews/Avyantra Health Technologies-moongat.json
Labels: crowdsourced review

#334 Add review
  reviews/Mifos Community App_kawedi.json
Labels: crowdsourced review, pending review

#335 Add review
  reviews/Mifos Community App_hc8756.json
Labels: crowdsourced review, pending review

#336 Add review
  reviews/VIPS_evh5516.json
Labels: crowdsourced review

#337 Add review
  reviews/Mifos Community App_Zytion.json
Labels: crowdsourced review

#338 Add review
  reviews/OpenG2P_MoralCode.json
Labels: crowdsourced review

#340 Add review
  reviews/MET Norway Weather API_ohm7.json
Labels: crowdsourced review

#350 Add review
  reviews/Bahmni_edwardtay.json
Labels: crowdsourced review

#354 Add review
  reviews/Mojaloop_nancyjlau.json
Labels: crowdsourced review

#356 Add review
  reviews/Apache Fineract_mxggie-wxng.json
Labels: crowdsourced review

#355 Add review
  reviews/Apache Fineract_nancyjlau.json
Labels: crowdsourced review

#357 Add review
  reviews/Mojaloop_SondosAhmed.json
Labels: crowdsourced review

#358 Add review
  reviews/X-Road_SondosAhmed.json
Labels: crowdsourced review

#367 Add review
  reviews/VIPS_rachita19082.json
Labels: crowdsourced review

#360 Add nominees for Digital Public Goods
  nominees/climatemachine.json
  nominees/eduactiv8.json
  nominees/nmf-earth
  nominees/plant-for-the-planet.json
  nominees/teammates.json
Labels: nomination

#370 Add Nominee: Africa COVID-19 Response Toolkit (ACRT)
  nominees/awareness-sms.json
  nominees/awareness-website.json
  nominees/bot-starter-kit.json
  nominees/emergency-relief-package-tracker.json
  nominees/heroes-bot.json
  nominees/housing-vacancy-bot.json
  nominees/internal-dashboard.json
  nominees/surveillance-forms.json
Labels: nomination, pending review

#373 Create apis.json
  nominees/apis.json
Labels: nomination

#376 Add review
  reviews/Primero_rachita19082.json
Labels: crowdsourced review

#377 Add review
  reviews/Avyantra Health Technologies_rachita19082.json
Labels: crowdsourced review

#374 Create opensustainabletech.json
  nominees/open-sustainable-technology.json
Labels: blocked, nomination

#372 Create foxBMS.json
  nominees/foxbms.json
Labels: blocked, nomination

#387 add nominees: open-sourced life-tracker Nomie
  nominees/nomie.json
Labels: nomination

#390 add nominee: The pudding - Women’s issues within political party platforms
  nominees/votes-for-women.json
Labels: nomination, pending review

#385 Add nominees from Impact Tracker (Data Analysis Tools)
  nominees/formpack.json
  nominees/power-bi-react.json
  nominees/qliksense-enterprise.json
  nominees/tabpy.json
Labels: nomination

#395 Add review
  reviews/DHIS2_Rolikasi.json
Labels: crowdsourced review, pending review

#396 Add review
  reviews/Avyantra Health Technologies_Rolikasi.json
Labels: crowdsourced review

#397 Add review
  reviews/Mifos Community App_Rolikasi.json
Labels: crowdsourced review, pending review

#401 Add review
  reviews/Primero_318anushka.json
Labels: crowdsourced review, pending review

#402 Add review
  reviews/Mojaloop_318anushka.json
Labels: crowdsourced review, pending review

#406 Add review
  reviews/Bahmni_ijeomaemeruwa.json
Labels: crowdsourced review, pending review

#405 CI: open_pr implemented to handle deleted files
  scripts/open_pr.js
Labels: enhancement

#408 Create camelot.json
  nominees/camelot.json
Labels: nomination, pending review

#382 Add nominees from Impact Tracker (GIS Tools)
  nominees/cartodb.json
Labels: nomination, pending review

#410 Add review
  reviews/Apache Fineract_ijeomaemeruwa.json
Labels: crowdsourced review

#411 Add review
  reviews/Avyantra Health Technologies_ijeomaemeruwa.json
Labels: crowdsourced review

#412 Add review
  reviews/Primero_ijeomaemeruwa.json
Labels: crowdsourced review

#413 Add review
  reviews/Mojaloop_ijeomaemeruwa.json
Labels: crowdsourced review

#414 Add review
  reviews/Modular Open Source Identity Platform_ijeomaemeruwa.json
Labels: crowdsourced review, pending review

#415 Add review
  reviews/DHIS2_ijeomaemeruwa.json
Labels: crowdsourced review

#409 Add nominee from impact tracker (remote sensors)
  nominees/rainforest-connection.json
Labels: nomination, pending review

#451 Added nominee: Project AEDES
  nominees/project-aedes.json
Labels: nomination, pending review

#433 Updated nominee: Nubian
  nominees/nubian.json
  nominees/project-konko.json
Labels: nomination, pending review

#491 Add definition of DPG in ReadMe
  README.md
Labels: Documentation
