Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2021-05, with the labels that each got.

#490 add nominee: Aleph
  nominees/aleph.json
Labels: nomination, pending review

#506 Modified screening schema
  screening-schema.json
Labels: enhancement

#489 add nominee: Emoncms
  nominees/emoncms.json
Labels: nomination

#488 add nominee: Open Source Energy Management System
  nominees/openems.json
Labels: nomination, pending review

#431 Create nominees
  focus.json
  nominees/onsset.json
  nominees/open-source-ecology.json
  nominees/openbci.json
  nominees/viame.json
Labels: nomination

#493 add nominee: brain-computer interfacing
  nominees/openbci-gui.json
Labels: nomination, pending review

#416 Add review
  reviews/DHIS2_llbrito.json
Labels: crowdsourced review, pending review

#417 Add review
  reviews/Mifos Community App_ijeomaemeruwa.json
Labels: crowdsourced review, pending review

#419 Add review
  reviews/Avyantra Health Technologies_vaishnavi-ch.json
Labels: crowdsourced review, pending review

#420 Add review
  reviews/Bahmni_vaishnavi-ch.json
Labels: crowdsourced review, pending review

#422 Add review
  reviews/DHIS2_vaishnavi-ch.json
Labels: crowdsourced review, pending review

#423 Add review
  reviews/MET Norway Weather API_ijeomaemeruwa.json
Labels: crowdsourced review, pending review

#425 Add review
  reviews/Primero_Bozena611.json
Labels: crowdsourced review, pending review

#421 Add review
  reviews/Primero_vaishnavi-ch.json
Labels: crowdsourced review, pending review

#427 Add review
  reviews/MET Norway Weather API_Bozena611.json
Labels: crowdsourced review, pending review

#434 Add review
  reviews/Bahmni_zubedauk.json
Labels: crowdsourced review, pending review

#437 Add review
  reviews/Apache Fineract_rachita19082.json
Labels: crowdsourced review, pending review

#436 Add review
  reviews/X-Road_rachita19082.json
Labels: crowdsourced review, pending review

#435 Add review
  reviews/Mojaloop_rachita19082.json
Labels: crowdsourced review, pending review

#438 Add review
  reviews/Avyantra Health Technologies_mxggie-wxng.json
Labels: crowdsourced review, pending review

#440 Add review
  reviews/MET Norway Weather API_Msgl.json
Labels: crowdsourced review, pending review

#442 Add review
  reviews/Mojaloop_Msgl.json
Labels: crowdsourced review, pending review

#445 Add review
  reviews/X-Road_Msgl.json
Labels: crowdsourced review, pending review

#441 Add review
  reviews/Apache Fineract_vaishnavi-ch.json
Labels: crowdsourced review, pending review

#443 Add review
  reviews/Mifos Community App_vaishnavi-ch.json
Labels: crowdsourced review, pending review

#444 Add review
  reviews/VIPS_vaishnavi-ch.json
Labels: crowdsourced review, pending review

#446 Add review
  reviews/Mojaloop_vaishnavi-ch.json
Labels: crowdsourced review, pending review

#447 Add review
  reviews/OpenCRVS_vaishnavi-ch.json
Labels: crowdsourced review, pending review

#449 Add review
  reviews/Apache Fineract_318anushka.json
Labels: crowdsourced review, pending review

#450 Add review
  reviews/OpenCRVS_318anushka.json
Labels: crowdsourced review, pending review

#474 Add review
  reviews/Bahmni_rachita19082.json
Labels: crowdsourced review, pending review

#448 Add review
  reviews/X-Road_ijeomaemeruwa.json
Labels: crowdsourced review, pending review

#485 Add review
  reviews/Primero_DivyanshiSingh.json
Labels: crowdsourced review, pending review

#486 Add review
  reviews/Bahmni_DivyanshiSingh.json
Labels: crowdsourced review, pending review

#487 Add review
  reviews/Avyantra Health Technologies_DivyanshiSingh.json
Labels: crowdsourced review, pending review

#496 Add review
  reviews/Mojaloop_Rolikasi.json
Labels: crowdsourced review, pending review

#498 Add review
  reviews/VIPS_Rolikasi.json
Labels: crowdsourced review, pending review

#499 Add review
  reviews/MET Norway Weather API_Rolikasi.json
Labels: crowdsourced review, pending review

#497 Add review
  reviews/Bahmni_Rolikasi.json
Labels: crowdsourced review, pending review

#495 add nominee: Safecast
  nominees/safecast.json
Labels: nomination

#439 Add nominees for DPG
  nominees/apache-ctakes.json
  nominees/caisis.json
  nominees/cookie-consent.json
  nominees/intermine.json
  nominees/labkey-server.json
  nominees/oncoscape.json
  nominees/orange.json
  nominees/tensorflow.json
  nominees/the-chris-project.json
Labels: nomination

#424 Add nominee: Open Collective
  nominees/open-collective.json
Labels: nomination

#505 Add nominee: High Resolution Population Density Estimates
  nominees/high-resolution-population-density-estimates.json
Labels: nomination, pending review

#465 Add nominee: Project Sidewalk
  nominees/project-sidewalk.json
Labels: nomination, pending review

#483 Add nominee: Liquid Prep
  nominees/liquid-prep.json
Labels: nomination, pending review

#481 Add nominee: Project Lockdown
  nominees/project-lockdown.json
Labels: nomination, pending review

#480 Add nominee: 2020PoliceBrutality
  nominees/2020policebrutality.json
Labels: nomination, pending review

#479 Add nominee: freeCodeCamp
  nominees/freecodecamp.json
Labels: nomination, pending review

#494 add nominee: BrainFlow
  nominees/brainflow.json
Labels: nomination, pending review

#461 Add new nominees
  nominees/bemserver.json
  nominees/bigbluebutton.json
  nominees/gcompris.json
  nominees/gibbon.json
  nominees/hedy.json
  nominees/openremote.json
Labels: nomination

#471 Add nominee: Cactus
  nominees/cactus.json
Labels: nomination

#383 Add nominee: Immunization Calculation Engine (ICE)
  nominees/immunization-calculation-engine.json
Labels: nomination, pending review

#510 Update nominee: A11y Project
  nominees/a11y-project.json
Labels: nomination, pending review

#472 Add nominees: Open AI Models
  nominees/apache-mahout.json
  nominees/caffe.json
  nominees/open-nn.json
  nominees/scikit-learn.json
Labels: nomination, pending review

#469 Add new nominees for Goal: Sustainable Investment
  nominees/invest.json
  nominees/remind.json
  nominees/system-advisor-model.json
Labels: nomination, pending review

#463 Add new nominees for SDG 3
  nominees/openemr.json
  nominees/openhospital.json
  nominees/pophealth.json
  nominees/vista.json
  nominees/zeprs.json
Labels: nomination

#514 Moved FOCUS project from root to nominees directory
  nominees/focus.json
Labels: pending review

#381 Add nominees from Africa Covid-19 Response Toolkit
  nominees/africa-covid-19-response-toolkit:-aws-infrastructure.json
  nominees/africa-covid-19-response-toolkit:-covid-19-api.json
Labels: nomination, pending review

#517 Update nominee: Healthsites to Global Healthsites Mapping Project
  nominees/global-healthsites-mapping-project.json
  nominees/healthsites.io.json
Labels: nomination, pending review

#516 Update nominee: Avni (OpenCHS)
  nominees/avni-client.json
  nominees/avni-server.json
  nominees/avni.json
Labels: nomination, pending review

#519 Added nominee: Community Health Toolkit
  nominees/community-health-toolkit.json
  nominees/medic-mobile.json
Labels: nomination, pending review

#520 Update nominee: OpenMRS
  nominees/openmrs-android-client.json
  nominees/openmrs-core.json
  nominees/openmrs.json
Labels: nomination

#521 Add nominee: Accessmod
  nominees/accessmod.json
Labels: nomination

#522 Add nominee: DIVOC
  nominees/divoc.json
Labels: nomination

#523 Update nominee: CommCare
  nominees/commcare-android.json
  nominees/commcare-cloud.json
  nominees/commcare.json
Labels: nomination

#525 Update nominee: mHero
  nominees/mhero.json
Labels: nomination

#529 Update nominee: StarHealth
  nominees/starhealth.json
Labels: nomination

#528 Update nominee: GOFR
  nominees/global-open-facility-registry.json
Labels: nomination, pending review

#527 Update nominee: KoboToolbox
  nominees/formpack.json
  nominees/kobo-api.json
  nominees/kobotoolbox.json
Labels: nomination

#526 Add nominee: OpenSRP
  nominees/open-smart-register-program.json
  nominees/opensrp.json
Labels: nomination

#532 Update nominee: OpenELIS
  nominees/open-electronic-laboratory-information-system.json
Labels: nomination, pending review

#533 Update nominee: KoboToolbox
  nominees/kobotoolbox.json
Labels: nomination, pending review

#515 Encode full submission for Project AEDES into JSON
  screening/project-aedes.json
Labels: pending review, screening

#534 Update nominee: Avyantra Health Technologies
  nominees/avyantra-health-technologies.json
Labels: pending review, screening

#531 Add nominee: EduNOSS
  nominees/edunoss.json
Labels: nomination

#541 Encode DIVOC full submission into JSON
  digitalpublicgoods/divoc.json
  nominees/divoc.json
Labels: Digital Public Good, pending review

#542 Encode CommCare full submission into JSON
  digitalpublicgoods/commcare-android.json
  digitalpublicgoods/commcare-cloud.json
  digitalpublicgoods/commcare.json
  nominees/commcare.json
Labels: Digital Public Good, pending review

#540 Encode full submission into JSON: OpenMRS
  digitalpublicgoods/openmrs.json
  nominees/openmrs.json
Labels: Digital Public Good, pending review

#544 Encode OpenSRP full submission into JSON
  digitalpublicgoods/opensrp.json
  nominees/opensrp.json
Labels: Digital Public Good, pending review
