Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2021-03, with the labels that each got.

#339 Add nominee: Delve
  nominees/delve.json
Labels: nomination

#341 Removed redundant fields from screening schema under indicator 7
  screening-schema.json
  screening/apache-fineract.json
  screening/avyantra-health-technologies.json
  screening/bahmni.json
  screening/dhis2.json
  screening/met-norway-weather-api.json
  screening/mifos-community-app.json
  screening/modular-open-source-identity-platform.json
  screening/mojaloop.json
  screening/opencrvs.json
  screening/openg2p.json
  screening/primero.json
  screening/vips.json
  screening/x-road.json
Labels: pending review

#343 Update Foodsoft
  nominees/foodsoft.json
Labels: nomination

#344 Add nominee: OpenAgro (Open Source Precision Agriculture with Drones)
  nominees/openagro.json
Labels: nomination

#348 Create bloom.json
  nominees/bloom.json
Labels: nomination

#351 updated SDGs field and added stage field in Template section
  CONTRIBUTING.md
Labels: Documentation

#347 Add nominee: Glific
  nominees/glific.json
Labels: nomination, pending review

#352 Create flood-maps.json
  nominees/flood-maps.json
Labels: nomination

#353 Add nominee: Collect Earth
  nominees/collect-earth.json
Labels: nomination

#366 Add nominee: Wikigender
  nominees/wikigender.json
Labels: nomination

#371 DOC: Updated CONTRIBUTING
  CONTRIBUTING.md
Labels: Documentation
