Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2021-06, with the labels that each got.

#547 Encode StarHealth full submission into JSON
  digitalpublicgoods/starhealth.json
Labels: Digital Public Good, pending review

#546 Encode GOFR full submission into JSON
  digitalpublicgoods/global-open-facility-registry.json
  nominees/global-open-facility-registry.json
Labels: Digital Public Good, pending review

#552 Update OpenSRP copyright & trademark information
  digitalpublicgoods/opensrp.json
Labels: Digital Public Good

#551 Add nominee: Safe YOU
  nominees/safe-you.json
Labels: nomination

#561 Update nominee: Safe YOU
  nominees/safe-you.json
Labels: nomination, pending review

#564 Add nominee: ODK
  nominees/odk-aggregate.json
  nominees/odk-briefcase.json
  nominees/odk-build.json
  nominees/odk-collect.json
  nominees/odk-xls-form-offline.json
  nominees/odk.json
Labels: nomination

#539 Encode submission into JSON: Community Health Toolkit (CHT)
  digitalpublicgoods/community-health-toolkit.json
  nominees/community-health-toolkit.json
Labels: Digital Public Good

#565 Add DPG: ODK
  digitalpublicgoods/odk.json
Labels: Digital Public Good

#569 Update nominee: ODK
  nominees/odk.json
Labels: Digital Public Good

#568 Add nominee: Platform for Real-time Impact and Situation Monitoring
  nominees/platform-for-real-time-impact-and-situation-monitoring.json
Labels: nomination

#518 Add nominee: Kiva Protocol
  nominees/kiva-protocol.json
Labels: nomination

#545 Encode KoboToolbox submission into JSON
  digitalpublicgoods/kobotoolbox.json
  nominees/kobotoolbox.json
Labels: Digital Public Good

#578 BLD: propagating unicef/publicgoods-scripts#19
  scripts/push.bash
Labels: enhancement

#574 Add nominee: PxWeb
  nominees/pxweb.json
Labels: nomination

#537 Add nominee: EduNOSS
  nominees/edunoss.json
Labels: nomination

#548 Add nominee: Project Konko
  nominees/project-konko.json
Labels: nomination

#587 Add nominee: Statbus
  nominees/statbus.json
Labels: nomination, pending review

#589 BUG: update CI to Node v16
  .github/workflows/auto.yml
Labels: bug

#590 Add nominee: SORMAS
  nominees/surveillance-outbreak-response-management-and-analysis-system.json
Labels: nomination

#593 Update nominee: RapidPro
  nominees/rapidpro.json
Labels: nomination

#543 Encode mHero full submission into JSON
  digitalpublicgoods/mhero.json
  nominees/mhero.json
Labels: Digital Public Good

#576 Add nominee: Sanitation Digital Solutions Platform
  nominees/sanitation-digital-solutions-platform.json
Labels: nomination

#538 Encode submission into JSON: Global Healthsites Mapping Project
  digitalpublicgoods/global-healthsites-mapping-project.json
  nominees/global-healthsites-mapping-project.json
Labels: Digital Public Good, Health Community of Practice, Immunization Delivery Management

#600 MAINT: propagate unicef/publicgoods-scripts#18
  scripts/push.bash
Labels: bug

#596 Add DPG: RapidPro
  digitalpublicgoods/rapidpro.json
  nominees/rapidpro.json
Labels: Digital Public Good, Health Community of Practice, Immunization Delivery Management

#591 Add DPG: SORMAS
  digitalpublicgoods/surveillance-outbreak-response-management-and-analysis-system.json
  nominees/surveillance-outbreak-response-management-and-analysis-system.json
Labels: Digital Public Good

#566 Add DPG: Kiva Protocol
  digitalpublicgoods/kiva-protocol.json
  nominees/kiva-protocol.json
Labels: Digital Public Good

#585 Add nominee: VRapeutic
  nominees/vrapeutic.json
Labels: nomination

#582 Add DPG: EduNOSS
  digitalpublicgoods/edunoss.json
  nominees/edunoss.json
Labels: Digital Public Good

#599 Add nominee: elimu.ai
  nominees/elimu.ai.json
Labels: nomination

#560 Add DPG: Safe YOU
  digitalpublicgoods/safe-you.json
  nominees/safe-you.json
Labels: Digital Public Good

#577 Add DPG: PxWeb
  digitalpublicgoods/pxweb.json
  nominees/activityinfo-python.json
  nominees/apache-ctakes.json
  nominees/apache-mahout.json
  nominees/bemserver.json
  nominees/caffe.json
  nominees/caisis.json
  nominees/collect-earth.json
  nominees/datawinners.json
  nominees/flood-maps.json
  nominees/focus.json
  nominees/gcompris.json
  nominees/intermine.json
  nominees/invest.json
  nominees/onsset.json
  nominees/open-electronic-laboratory-information-system.json
  nominees/open-foris-collect-mobile.json
  nominees/open-foris-collect.json
  nominees/openhospital.json
  nominees/pxweb.json
  nominees/system-advisor-model.json
  nominees/tabpy.json
  nominees/the-chris-project.json
  nominees/vista.json
Labels: Digital Public Good
