Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2021-02, with the labels that each got.

#317 BLD: autogenerate API
  .github/workflows/main.yml
  package-lock.json
  package.json
  scripts/api.js
Labels: enhancement

#318 BUG: fix missing dep in #317
  package-lock.json
  package.json
Labels: bug

#280 Add nominee: Period Dignity Bristol
  nominees/period-dignity-bristol.json
Labels: nomination

#184 Add nominee: Project Connect
  nominees/project-connect.json
Labels: nomination

#315 Renamed 2 indicators: Clear Ownership & Platform Independence
  screening-schema.json
  screening/apache-fineract.json
  screening/avyantra-health-technologies.json
  screening/dhis2.json
  screening/mifos-community-app.json
  screening/modular-open-source-identity-plaform.json
  screening/mojaloop.json
  screening/opencrvs.json
  screening/openg2p.json
  screening/primero.json
  screening/x-road.json
Labels: enhancement

#320 Encoded MET Norway full submission into JSON
  nominees/met-norway-weather-api.json
  screening/met-norway-weather-api.json
Labels: pending review, screening

#313 Encoded VIPS full submission into JSON
  nominees/vips.json
  screening/vips.json
Labels: pending review, screening

#323 Add nominee: Bahmni (www.bahmni.org)
  nominees/bahmni.json
  nominees/cboard.json
  nominees/hive.json
  nominees/integreat.json
  nominees/open-drone-suite.json
  nominees/vivoosvr.json
Labels: nomination

#173 Add nominee: FarmBot
  nominees/farmbot.json
Labels: nomination

#325 Propagate suggested change in indicator 7
  screening-schema.json
  screening/apache-fineract.json
  screening/avyantra-health-technologies.json
  screening/dhis2.json
  screening/met-norway-weather-api.json
  screening/mifos-community-app.json
  screening/modular-open-source-identity-plaform.json
  screening/mojaloop.json
  screening/opencrvs.json
  screening/openg2p.json
  screening/primero.json
  screening/vips.json
  screening/x-road.json
Labels: pending review

#326 Encode Bahmni full submission into JSON
  nominees/bahmni.json
  screening/bahmni.json
Labels: screening
