Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2021-09, with the labels that each got.

#571 Add review
  reviews/DIVOC_Ainali.json
Labels: crowdsourced review

#584 Add review
  reviews/StarHealth_Ainali.json
Labels: crowdsourced review

#399 Add review
  reviews/VIPS_llbrito.json
Labels: pending review, crowdsourced review

#688 Add nominee: OTTAA Project
  nominees/ottaa-project.json
Labels: nomination, pending review

#693 Add Local Help Guide: Help Center
  README.md
  docs/help-center/best-practices.md
  docs/help-center/documentation.md
  docs/help-center/open-standards.md
Labels: Documentation

#346 Add DPG: AI Agro
  digitalpublicgoods/ai-agro.json
  nominees/ai-agro.json
Labels: Digital Public Good, technical review, UNICEF Venture Fund

#614 Add nominee: Lily the Llama Helps Her Herd
  nominees/lily-the-llama-helps-her-herd.json
Labels: nomination, pending review

#651 Add DPG: Open Drone Suite
  digitalpublicgoods/open-drone-suite.json
  nominees/open-drone-suite.json
Labels: Digital Public Good, technical review

#695 Update data exchange open standards
  docs/help-center/open-standards.md
Labels: Documentation

#631 Add DPGs: FAO Digital Services Portfolio
  digitalpublicgoods/fao-digital-services-portfolio-agrimarketplace.json
  digitalpublicgoods/fao-digital-services-portfolio-e-nutrifood.json
  digitalpublicgoods/fao-digital-services-portfolio-livestock.json
  digitalpublicgoods/fao-digital-services-portfolio-weather-and-crop-calendar.json
  nominees/fao-digital-services-portfolio-agrimarketplace.json
  nominees/fao-digital-services-portfolio-e-nutrifood.json
  nominees/fao-digital-services-portfolio-livestock.json
  nominees/fao-digital-services-portfolio-weather-and-crop-calendar.json
Labels: pending review, Digital Public Good, Climate Change Adaptation CoP, Weather & Climate Information Services

#659 Add DPG: ICE (Immunization Calculation Engine, Issue #555)
  digitalpublicgoods/immunization-calculation-engine.json
  nominees/immunization-calculation-engine.json
Labels: pending review, Digital Public Good, technical review

#698 Updated links in altinn.json
  digitalpublicgoods/altinn.json
Labels: Digital Public Good

#652 Add DPG: OpenLMIS (Issue #555)
  digitalpublicgoods/openlmis.json
  nominees/openlmis.json
Labels: Digital Public Good, technical review

#707 Update open-standards.md
  docs/help-center/open-standards.md
Labels: Documentation

#706 Update best practices: add material design to UI/ UX
  docs/help-center/best-practices.md
Labels: Documentation

#628 Add nominee: WaPOR
  nominees/water-productivity-open-access-portal.json
Labels: nomination, pending review, Climate Change Adaptation CoP

#583 Add DPG: Project Konko
  digitalpublicgoods/project-konko.json
Labels: pending review, Digital Public Good, technical review

#701 Add nominee: Find Your Immunization
  nominees/find-your-immunization.json
Labels: nomination, pending review

#705 Add nominee: Python Package Index
  nominees/python-package-index.json
Labels: nomination

#710 Updated DPG: Project Konko
  nominees/project-konko.json
Labels: pending review, Digital Public Good

#654 Add DPG: OpenIMIS (Issue #555)
  digitalpublicgoods/openimis.json
  nominees/openimis.json
Labels: pending review, Digital Public Good, technical review

#711 Remove nominee: Python Package Index (PyPI)
  nominees/python-package-index.json
Labels: nomination, pending review

#702 Add nominee: OpenFn Integration Toolkit
  nominees/openfn-integration-toolkit.json
Labels: nomination, pending review

#720 BUG: fix check-filenames script
  nominees/africa-covid-19-response-toolkit-awareness-sms.json
  nominees/africa-covid-19-response-toolkit-awareness-website.json
  nominees/africa-covid-19-response-toolkit-aws-infrastructure.json
  nominees/africa-covid-19-response-toolkit-bot-starter-kit.json
  nominees/africa-covid-19-response-toolkit-covid-19-api.json
  nominees/africa-covid-19-response-toolkit-emergency-relief-package-tracker.json
  nominees/africa-covid-19-response-toolkit-heroes-bot.json
  nominees/africa-covid-19-response-toolkit-housing-vacancy-bot.json
  nominees/africa-covid-19-response-toolkit-internal-dashboard.json
  nominees/africa-covid-19-response-toolkit-surveillance-forms.json
  nominees/firma.json
  nominees/redirect-2-redirectioneaza.ro.json
  scripts/check-filenames.bash
Labels: bug
