Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2021-07, with the labels that each got.

#592 Add nominee: NotesMaster
  nominees/notesmaster.json
Labels: nomination, pending review

#608 Add nominee: Open Risk Manual
  nominees/open-risk-manual.json
Labels: nomination, pending review

#602 Add nominee: Bisa Health
  nominees/bisa-health.json
Labels: nomination

#621 Add nominees: FAO Digital Services Portfolio
  nominees/fao-digital-services-portfolio-agrimarketplace.json
  nominees/fao-digital-services-portfolio-e-nutrifood.json
  nominees/fao-digital-services-portfolio-livestock.json
  nominees/fao-digital-services-portfolio-weather-and-crop-calendar.json
Labels: nomination, pending review

#630 Add nominee: MERON
  nominees/meron.json
Labels: nomination

#626 Add nominee: Coronasafe Care
  nominees/care.json
  nominees/coronasafe-care.json
Labels: nomination

#633 Add nominee: Fedora Linux
  nominees/fedora-linux.json
Labels: nomination, pending review

#639 Add DPG: Standard for Public Code
  digitalpublicgoods/standard-for-public-code.json
Labels: Digital Public Good, pending review, technical review

#637 Add nominee: Open Terms Archive
  nominees/coronasafe-care.json
  nominees/elimu.ai.json
  nominees/fao-digital-services-portfolio-agrimarketplace.json
  nominees/fao-digital-services-portfolio-e-nutrifood.json
  nominees/fao-digital-services-portfolio-livestock.json
  nominees/fao-digital-services-portfolio-weather-and-crop-calendar.json
  nominees/open-terms-archive.json
  nominees/statbus.json
  nominees/vrapeutic.json
Labels: nomination, pending review

#662 Update nominee: Standard For Public Code
  nominees/standard-for-public-code.json
Labels: Digital Public Good

#667 Update nominee: Glific
  nominees/glific.json
Labels: nomination

#666 Add nominee: OSCAR
  nominees/oscar.json
Labels: nomination, pending review
