Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2021-01, with the labels that each got.

#179 Add review
  reviews/.gitkeep
  reviews/Mojaloop-CriLoma.json
Labels: crowdsourced review

#180 Add review
  reviews/OpenG2P-Timidan.json
Labels: crowdsourced review

#181 Add review
  reviews/X-Road-hhio618.json
Labels: crowdsourced review

#182 Add review
  reviews/Avyantra Health Technologies-yashgo0018.json
Labels: crowdsourced review

#183 Add review
  reviews/Mojaloop-developerfred.json
Labels: crowdsourced review

#185 Add review
  reviews/OpenG2P-shekharmishra51.json
Labels: crowdsourced review

#187 Add review
  reviews/Mojaloop-jonasgrilleres.json
Labels: crowdsourced review

#188 Add review
  reviews/Avyantra Health Technologies-tosinamuda.json
Labels: crowdsourced review

#189 Add review
  reviews/Mojaloop-selinaxkyle.json
Labels: crowdsourced review

#190 Add review
  reviews/OpenG2P-gokulsan.json
Labels: crowdsourced review

#191 Add review
  reviews/Apache Fineract-gokulsan.json
Labels: crowdsourced review

#192 Add review
  reviews/Avyantra Health Technologies-spiritbro1.json
Labels: crowdsourced review

#193 Add review
  reviews/OpenG2P-QParkinson.json
Labels: crowdsourced review

#194 Add review
  reviews/Avyantra Health Technologies-johnmgrimm.json
Labels: crowdsourced review

#195 Add review
  reviews/Apache Fineract-npbates.json
Labels: crowdsourced review

#196 Add review
  reviews/Mifos Community App-npbates.json
Labels: crowdsourced review

#197 Add review
  reviews/Avyantra Health Technologies-npbates.json
Labels: crowdsourced review

#198 Add review
  reviews/OpenCRVS-pcuellar.json
Labels: crowdsourced review

#199 Add review
  reviews/Mojaloop-raducara.json
Labels: crowdsourced review

#200 Add review
  reviews/Apache Fineract-pipi333.json
Labels: crowdsourced review

#201 Add review
  reviews/OpenG2P-dogracer.json
Labels: crowdsourced review

#205 Add review
  reviews/Apache Fineract-erazhu31.json
Labels: crowdsourced review

#209 Add review
  reviews/Mojaloop-phog45.json
Labels: crowdsourced review

#211 Add review
  reviews/Avyantra Health Technologies-phog45.json
Labels: crowdsourced review

#214 public-goods-candidates
  reviews/Mojaloop-guiflor.json
Labels: crowdsourced review

#216 unicef-public-goods-candidates-1
  reviews/OpenCRVS-guiflor.json
Labels: crowdsourced review

#217 Add review
  reviews/Modular Open Source Identity Plaform-526375828.json
Labels: crowdsourced review

#219 Add review
  reviews/OpenG2P-BlankerL.json
Labels: crowdsourced review

#220 Add review
  reviews/Mifos Community App-MrGee198.json
Labels: crowdsourced review

#221 Add review
  reviews/X-Road-MrGee198.json
Labels: crowdsourced review

#222 Add review
  reviews/Apache Fineract-MrGee198.json
Labels: crowdsourced review

#223 Add review
  reviews/Mojaloop-devranjan.json
Labels: crowdsourced review

#224 Add review
  reviews/Apache Fineract-KZFlyer.json
Labels: crowdsourced review

#225 Add review
  reviews/OpenG2P-KZFlyer.json
Labels: crowdsourced review

#226 Add review
  reviews/DHIS2-twood25.json
Labels: crowdsourced review

#228 Add review
  reviews/Modular Open Source Identity Plaform-yulucket.json
Labels: crowdsourced review

#229 Add review
  reviews/Mojaloop-zjicmyw.json
Labels: crowdsourced review

#230 Add review
  reviews/Mojaloop-compandcode.json
Labels: crowdsourced review

#231 Add review
  reviews/Avyantra Health Technologies-Amircode2050.json
Labels: crowdsourced review

#232 Add review
  reviews/Mojaloop-Amircode2050.json
Labels: crowdsourced review

#233 Add review
  reviews/OpenCRVS-Amircode2050.json
Labels: crowdsourced review

#234 Add review
  reviews/Mifos Community App-Amircode2050.json
Labels: crowdsourced review

#235 Add review
  reviews/Apache Fineract-RaynH20.json
Labels: crowdsourced review

#247 Add review
  reviews/Apache Fineract-BeAnMo.json
Labels: crowdsourced review

#248 Add review
  reviews/Mojaloop-Joe-mcgee.json
Labels: crowdsourced review

#249 Add review
  reviews/X-Road-vgweiner.json
Labels: crowdsourced review

#250 Add review
  reviews/DHIS2-askaaqib.json
Labels: crowdsourced review

#251 Add review
  reviews/Apache Fineract-askaaqib.json
Labels: crowdsourced review

#252 Add review
  reviews/X-Road-askaaqib.json
Labels: crowdsourced review

#253 Add review
  reviews/Apache Fineract-Ryan-Gordon.json
Labels: crowdsourced review

#255 Add review
  reviews/Avyantra Health Technologies-gitati16.json
Labels: crowdsourced review

#257 Add review
  reviews/Mojaloop-SchickMarkus.json
Labels: crowdsourced review

#258 Add review
  reviews/OpenCRVS-apuyou.json
Labels: crowdsourced review

#259 Add review
  reviews/Avyantra Health Technologies-Revanshill.json
Labels: crowdsourced review

#260 Add review
  reviews/DHIS2-Rysa1981.json
Labels: crowdsourced review

#261 Add review
  reviews/OpenG2P-Rysa1981.json
Labels: crowdsourced review

#262 Add review
  reviews/Mojaloop-MohsenKhosravinia.json
Labels: crowdsourced review

#263 Add review
  reviews/Avyantra Health Technologies-truetechcode.json
Labels: crowdsourced review

#264 Add review
  reviews/Modular Open Source Identity Plaform-truetechcode.json
Labels: crowdsourced review

#273 Add review
  reviews/Avyantra Health Technologies-YannikOtt.json
Labels: crowdsourced review

#274 Add review
  reviews/X-Road-YannikOtt.json
Labels: crowdsourced review

#266 Add review
  reviews/Apache Fineract-gkimbwala.json
Labels: crowdsourced review

#275 Add review
  reviews/OpenG2P-YannikOtt.json
Labels: crowdsourced review

#277 Add review
  reviews/Apache Fineract-Sentouky12.json
Labels: crowdsourced review

#276 Add review
  reviews/OpenCRVS-Sentouky12.json
Labels: crowdsourced review

#278 Add review
  reviews/OpenG2P-aga7hokakological.json
Labels: crowdsourced review

#279 Add review
  reviews/OpenG2P-wakeful156.json
Labels: crowdsourced review

#281 Add review
  reviews/DHIS2-ManyRios.json
Labels: crowdsourced review

#282 Add review
  reviews/DHIS2-fneitzel.json
Labels: crowdsourced review

#285 Add review
  reviews/Mojaloop-Barukimang.json
Labels: crowdsourced review

#286 Add review
  reviews/DHIS2-matimaone1.json
Labels: crowdsourced review

#288 Add review
  reviews/X-Road-Amircode2050.json
Labels: crowdsourced review

#290 Add review
  reviews/Mifos Community App-javipus.json
Labels: crowdsourced review

#291 Add review
  reviews/Modular Open Source Identity Plaform-feixingxiaozi.json
Labels: crowdsourced review

#292 Add review
  reviews/OpenG2P-hackleberryfinn.json
Labels: crowdsourced review

#293 Add review
  reviews/OpenG2P-dgparks.json
Labels: crowdsourced review

#294 Add review
  reviews/X-Road-leylas-acclab.json
Labels: crowdsourced review

#296 Add review
  reviews/Modular Open Source Identity Plaform-bejarano-tech.json
Labels: crowdsourced review

#297 Add review
  reviews/Modular Open Source Identity Plaform-dr-streur.json
Labels: crowdsourced review

#298 Add review
  reviews/Avyantra Health Technologies-daworm277.json
Labels: crowdsourced review

#300 Add review
  reviews/OpenCRVS-bejarano-tech.json
Labels: crowdsourced review

#301 Add review
  reviews/OpenG2P-Amircode2050.json
Labels: crowdsourced review

#302 Add review
  reviews/DHIS2-Amircode2050.json
Labels: crowdsourced review

#289 Add review
  reviews/Mojaloop-nataliabayonab.json
Labels: crowdsourced review

#186 Add review
  reviews/Primero-ericboucher.json
Labels: crowdsourced review

#202 Add review
  reviews/OpenG2P-saveascj.json
Labels: crowdsourced review

#206 Add review
  reviews/Primero-jeanesims.json
Labels: crowdsourced review

#208 Add review
  reviews/Primero-victespinoza.json
Labels: crowdsourced review

#215 Add review
  reviews/Primero-babak-gholampour.json
Labels: crowdsourced review

#236 Add review
  reviews/Primero-emmaling27.json
Labels: crowdsourced review

#265 Add review
  reviews/Modular Open Source Identity Plaform-brunocoelhommn.json
Labels: crowdsourced review

#287 Add review
  reviews/Primero-OS-the-Person.json
Labels: crowdsourced review

#295 Add review
  reviews/Primero-leylas-acclab.json
Labels: crowdsourced review

#303 Add review
  reviews/Avyantra Health Technologies-upretiprateek.json
Labels: crowdsourced review

#166 Add nominee: An Open Multipurpose Extensible Aerial Platform
  nominees/open-drone-suite.json
Labels: nomination, pending review

#163 Add nominee: Oky: the mobile phone period tracker app for girls
  nominees/oky.json
Labels: nomination

#218 Add nominee: VivoosVR
  nominees/vivoosvr.json
Labels: nomination

#299 Add nominee: Hive: Drone Monitoring and Management System
  nominees/drone-management-system.json
  nominees/hive.json
Labels: nomination

#306 Add nominee: VIPS
  nominees/vips.json
Labels: nomination
