Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2021-11, with the labels that each got.

#830 Add review
  reviews/Community Health Toolkit_MHLoppy.json
Labels: crowdsourced review

#850 Add nominee: freewat
  nominees/freewat.json
Labels: nomination

#851 Add nominee: VictimsOfIntolerance
  nominees/victimsofintolerance.json
Labels: nomination

#756 Add nominee: total11y
  nominees/total11y
Labels: nomination

#792 Add nominee: Mentee
  nominees/mentee.json
Labels: nomination

#731 Add nominee: ScioXR
  nominees/scioxr
Labels: nomination

#712 Add nominee: impactMarket
  nominees/impactmarket.json
Labels: nomination

#798 Update nominee: signdict
  nominees/signdict.json
Labels: nomination

#775 Add nominee: epanet
  nominees/epanet.json
Labels: nomination

#813 Add nominee: The Odin Project
  nominees/the-odin-project.json
Labels: nomination

#762 Add nominee: Gender gap tracker
  nominees/gender-gap-tracker.json
Labels: nomination

#780 Add nominee: python-for-power-system-analysis
  nominees/pypsa.json
Labels: nomination

#765 Add nominee: OpenTeleRehab
  nominees/opentelerehab.json
Labels: nomination, pending review

#779 Add nominee: open-source-energy-modelling-system
  nominees/osemosys.json
Labels: nomination

#789 Add nominee: Our World in Data
  nominees/our-world-in-data.json
Labels: nomination

#754 Add nominee: Hyperaudio
  nominees/hyperaudio.json
Labels: nomination

#793 Add nominee: SWITCH
  nominees/switch.json
Labels: nomination

#825 Add nominee: Oasis Loss Modelling Framework
  nominees/oasis-loss-modelling-framework.json
Labels: nomination

#856 Update nominee: PublicLab Plots2
  nominees/publiclab-plots2.json
Labels: nomination

#812 Add nominee: cupl NFC sensor platform
  nominees/cupl-nfc-sensor-platform.json
Labels: nomination

#853 Add nominee: openHAB
  nominees/openhab.json
Labels: nomination, pending review

#867 Add review
  reviews/Primero_downeymj.json
Labels: crowdsourced review

#866 Add review
  reviews/OpenMRS_downeymj.json
Labels: crowdsourced review

#865 Add review
  reviews/OpenCRVS_downeymj.json
Labels: crowdsourced review

#804 Add nominee: Detroit water project
  nominees/detroit-water-project.json
Labels: nomination, pending review

#791 Add nominee: Global Biodiversity Information Facility
  nominees/global-biodiversity-information-facility.json
Labels: nomination, pending review

#834 Add nominee: OpenDroneMap
  nominees/opendronemap.json
Labels: nomination

#770 Add nominee: intern
  excluded-nominees/README.md
  excluded-nominees/intern.json
Labels: nomination, pending review

#767 Update pxweb.json
  nominees/pxweb.json
Labels: nomination, pending review

#790 Add nominee: Youth Explorer
  nominees/wazimap.json
Labels: nomination, pending review

#862 Update nominee: Book Dash
  nominees/book-dash.json
Labels: nomination, pending review

#871 Update nominee: Somleng
  nominees/somleng.json
Labels: nomination, pending review

#550 Add nominee: Project Simoy
  nominees/project-simoy.json
Labels: nomination, pending review

#869 Add nominee: Open Referral
  nominees/open-referral.json
Labels: nomination, pending review

#774 Add nominee: OpenGeoScales
  nominees/opengeoscales.json
Labels: nomination

#857 Add nominee: project-kick-out-covid-19-infotech
  excluded-nominees/README.md
  excluded-nominees/project-kick-out-covid-19-infotech.json
Labels: nomination

#808 Add nominee: techsoup
  excluded-nominees/README.md
  excluded-nominees/techsoup.json
Labels: nomination, pending review

#718 Add DPG: Accessible Kazakhstan
  digitalpublicgoods/accessible-kazakhstan.json
Labels: Digital Public Good, Pathfinding pilots

#345 Add DPG: Delve
  digitalpublicgoods/delve.json
  nominees/delve.json
Labels: Digital Public Good, technical review

#715 Add nominee: The Atlas of Economic Complexity
  excluded-nominees/README.md
  excluded-nominees/the-atlas-of-economic-complexity.json
Labels: nomination, pending review

#873 Add review
  reviews/GlobaLeaks_downeymj.json
Labels: crowdsourced review

#872 Add review
  reviews/Glific_downeymj.json
Labels: crowdsourced review

#570 Add DPG: PRISM
  digitalpublicgoods/prism.json
Labels: Digital Public Good

#884 Add nominee: PRISM
  nominees/prism.json
Labels: nomination, pending review, Climate Change Adaptation CoP

#880 Add nominee: Climate Information Platform
  nominees/climate-information-platform.json
Labels: nomination, pending review, Climate Change Adaptation CoP

#881 Add DPG: Climate Information Platform
  digitalpublicgoods/climate-information-platform.json
  nominees/climate-information-platform.json
Labels: Digital Public Good, technical review, Climate Change Adaptation CoP

#886 Add DPG: Open Foris Collect
  digitalpublicgoods/open-foris-collect.json
  nominees/open-foris-collect.json
Labels: Digital Public Good, Climate Change Adaptation CoP

#885 Add nominee: SantéIMS
  nominees/santeims.json
Labels: nomination, pending review

#854 Exclude nominee: Frictionless Data
  excluded-nominees/README.md
  excluded-nominees/frictionless-data.json
Labels: nomination, pending review
