Repository DPGAlliance/publicgoods-candidates, pull requests merged in 2022-02, with the labels that each got.

#953 Update nominee: Lily the Llama Helps Her Herd
  nominees/lily-the-llama-helps-her-herd.json
Labels: nomination

#613 Add DPG: Lily the Llama Helps Her Herd
  digitalpublicgoods/lily-the-llama-helps-her-herd.json
Labels: Digital Public Good, technical review

#954 Update status: Lily the Llama Herds Her Herd
  nominees/lily-the-llama-helps-her-herd.json
Labels: Digital Public Good

#967 Exclude nominee: ActivityInfo Python Client
  excluded-nominees/README.md
  excluded-nominees/activityinfo-python.json
Labels: pending review

#971 Updating multiple changes
  nominee-schema.json
Labels: pending review, Documentation

#992 Exclude nominee: Ka Lite
  excluded-nominees/README.md
  excluded-nominees/ka-lite.json
Labels: excluded nomination

#1009 BUG: exclude lookingglass properly
  digitalpublicgoods/lookingglass.json
  nominees/lookingglass.json
Labels: bug

#996 Exclude nominee: OpenStax
  excluded-nominees/README.md
  excluded-nominees/open-stax.json
Labels: excluded nomination

#1029 [MAINTENANCE] Fix ordering of excluded nominees in README.md
  excluded-nominees/README.md
Labels: pending review
